version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0
  continuation: circleci/continuation@0.3.1
  dataworks: modular-data/dataworks-orb@0.0.17

main_only: &main_only
  branches:
    only: main

parameters:
  pipeline_ready:
    type: boolean
    default: true    
  environments:
    description: List of Environments, where Pipeline is Active
    type: string
    default: "development" # Comma Seperated Environments, Enable Pipeline Run - Doesnt work for Release Environment

commands:
  set-continued-config:
    parameters:
      pipeline-parameters-json-file:
        type: string
        default: /tmp/pipeline-parameters.json
      configuration-path:
        type: string
        default: .circleci/continue.yml
      lookup-key:
        type: string
        description: key to look up the filepath for the next config
      environments:
        description: List of Environments, where Pipeline is Active
        type: string
    steps:
      - run:
          name: Set next config as << parameters.configuration-path >>
          command: |
            cp $(jq -r '.<< parameters.lookup-key >>' << parameters.pipeline-parameters-json-file >>) << parameters.configuration-path >>

            # debug: confirm next config
            cat << parameters.configuration-path >> 
      - run:
          name: Pop << parameters.lookup-key >> key from << parameters.pipeline-parameters-json-file >>
          command: |
            jq 'del(.<< parameters.lookup-key >>)' << parameters.pipeline-parameters-json-file >> > params.json

            echo "Add Env Type..."
            jq '.environments="<< parameters.environments >>"' params.json > params_1.json

            # Evaluate if Pull Request
            if [ -z "${CIRCLE_PULL_REQUEST##*/}" ]
            then
              IS_PR=false
            else
              IS_PR=true
            fi
            jq ".is_pr=$IS_PR" params_1.json > params_2.json

            # CLeanup Obsolete Files
            rm << parameters.pipeline-parameters-json-file >> params_1.json params.json

            # Copy Latest Params 
            cp params_2.json << parameters.pipeline-parameters-json-file >>

            # debug: confirm contents
            jq '.' << parameters.pipeline-parameters-json-file >>

jobs:
  generic-trigger:
    parameters:
      environments:
        description: List of Environments, where Pipeline is Active
        type: string          
    executor: path-filtering/default
    resource_class: small
    steps: 
      - checkout      
      - path-filtering/set-parameters:
          base-revision: << pipeline.git.branch >>
          # NOTE: path-filtering mapping is basic and can be limiting.
          # - No comments allowed
          # - Each line can only have 3 items, separated by space
          # - No item in each line can have space in their value
          mapping: |
            .* config ".circleci/terraform-plan-apply.yml"
            ^((?!README.md).)*$ terraform true
            README.md skip true
      - set-continued-config:
          lookup-key: config
          environments: << parameters.environments >>
      - continuation/continue:
          # NOTE: for CircleCI Server customers, please set circleci_domain
          # See https://circleci.com/developer/orbs/orb/circleci/continuation#commands-continue
          configuration_path: .circleci/continue.yml
          # NOTE: this is the default output path of https://circleci.com/developer/orbs/orb/circleci/path-filtering#commands-set-parameters
          parameters: /tmp/pipeline-parameters.json

workflows:
  trigger-pipeline:
    when: 
      equal: [ true, << pipeline.parameters.pipeline_ready >> ]  
    jobs:
      - dataworks/aws_sync_to_s3:
          name: aws_s3_sync_artifacts
          bucket_prefix: dpr-glue-jobs
          environments: << pipeline.parameters.environments >>
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          notify_jira: false
          notify_slack: false
          path_suffix: configs
          exclude_app_name_from_dest_suffix: true
          sync_args: "--exclude '*' --include '*/*config.json' --delete --cli-connect-timeout 0 --cli-read-timeout 0"
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          src_artifacts: mappings
      - generic-trigger:
          name: generic-pipeline-trigger
          environments: << pipeline.parameters.environments >>
          requires: [aws_s3_sync_artifacts]
